<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/"
	targetNamespace="urn:be:e-contract:sts:example" xmlns:tns="urn:be:e-contract:sts:example"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsp="http://www.w3.org/ns/ws-policy"
	xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
	xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702"
	xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:wst="http://docs.oasis-open.org/ws-sx/ws-trust/200512"
	xmlns:wsa="http://www.w3.org/2005/08/addressing" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata"
	xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex">

	<types>
		<schema xmlns="http://www.w3.org/2001/XMLSchema">
			<import namespace="urn:be:e-contract:sts:example"
				schemaLocation="example.xsd" />
		</schema>
	</types>

	<message name="EchoRequest">
		<part name="EchoRequest" element="tns:EchoRequest" />
	</message>
	<message name="EchoResponse">
		<part name="EchoResponse" element="tns:EchoResponse" />
	</message>

	<portType name="ExampleServicePortType">
		<operation name="echo">
			<input message="tns:EchoRequest" />
			<output message="tns:EchoResponse" />
		</operation>
	</portType>

	<binding name="ExampleServiceBinding" type="tns:ExampleServicePortType">
		<wsp:PolicyReference URI="#ExamplePolicy" />
		<soap:binding transport="http://schemas.xmlsoap.org/soap/http"
			style="document" />
		<operation name="echo">
			<soap:operation />
			<input>
				<soap:body use="literal" />
			</input>
			<output>
				<soap:body use="literal" />
			</output>
		</operation>
	</binding>

	<binding name="ExampleServiceBinding2" type="tns:ExampleServicePortType">
		<wsp:PolicyReference URI="#ExamplePolicy2" />
		<soap:binding transport="http://schemas.xmlsoap.org/soap/http"
			style="document" />
		<operation name="echo">
			<soap:operation />
			<input>
				<soap:body use="literal" />
			</input>
			<output>
				<soap:body use="literal" />
			</output>
		</operation>
	</binding>

	<binding name="ExampleServiceBinding3" type="tns:ExampleServicePortType">
		<wsp:PolicyReference URI="#ExamplePolicy3" />
		<soap:binding transport="http://schemas.xmlsoap.org/soap/http"
			style="document" />
		<operation name="echo">
			<soap:operation />
			<input>
				<soap:body use="literal" />
			</input>
			<output>
				<soap:body use="literal" />
			</output>
		</operation>
	</binding>

	<binding name="ExampleServiceBinding4" type="tns:ExampleServicePortType">
		<wsp:PolicyReference URI="#ExamplePolicy4" />
		<soap:binding transport="http://schemas.xmlsoap.org/soap/http"
			style="document" />
		<operation name="echo">
			<soap:operation />
			<input>
				<soap:body use="literal" />
			</input>
			<output>
				<soap:body use="literal" />
			</output>
		</operation>
	</binding>

	<binding name="ExampleServiceBinding5" type="tns:ExampleServicePortType">
		<wsp:PolicyReference URI="#ExamplePolicy5" />
		<soap:binding transport="http://schemas.xmlsoap.org/soap/http"
			style="document" />
		<operation name="echo">
			<soap:operation />
			<input>
				<soap:body use="literal" />
			</input>
			<output>
				<soap:body use="literal" />
			</output>
		</operation>
	</binding>

	<binding name="ExampleServiceBinding6" type="tns:ExampleServicePortType">
		<wsp:PolicyReference URI="#ExamplePolicy6" />
		<soap:binding transport="http://schemas.xmlsoap.org/soap/http"
			style="document" />
		<operation name="echo">
			<soap:operation />
			<input>
				<soap:body use="literal" />
			</input>
			<output>
				<soap:body use="literal" />
			</output>
		</operation>
	</binding>

	<binding name="ExampleServiceBinding7" type="tns:ExampleServicePortType">
		<wsp:PolicyReference URI="#ExamplePolicy7" />
		<soap:binding transport="http://schemas.xmlsoap.org/soap/http"
			style="document" />
		<operation name="echo">
			<soap:operation />
			<input>
				<soap:body use="literal" />
			</input>
			<output>
				<soap:body use="literal" />
			</output>
		</operation>
	</binding>

	<service name="ExampleService">
		<port name="ExampleServicePort" binding="tns:ExampleServiceBinding">
			<soap:address location="http://localhost:8080/example" />
		</port>
		<port name="ExampleServicePort2" binding="tns:ExampleServiceBinding2">
			<soap:address location="http://localhost:8080/example2" />
		</port>
		<port name="ExampleServicePort3" binding="tns:ExampleServiceBinding3">
			<soap:address location="http://localhost:8080/example3" />
		</port>
		<port name="ExampleServicePort4" binding="tns:ExampleServiceBinding4">
			<soap:address location="http://localhost:8080/example4" />
		</port>
		<port name="ExampleServicePort5" binding="tns:ExampleServiceBinding5">
			<soap:address location="http://localhost:8080/example5" />
		</port>
		<port name="ExampleServicePort6" binding="tns:ExampleServiceBinding6">
			<soap:address location="http://localhost:8080/example6" />
		</port>
		<port name="ExampleServicePort7" binding="tns:ExampleServiceBinding7">
			<soap:address location="http://localhost:8080/example7" />
		</port>
	</service>

	<wsp:Policy wsu:Id="ExamplePolicy">
		<sp:SupportingTokens>
			<wsp:Policy>
				<sp:UsernameToken
					sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
					<wsp:Policy />
				</sp:UsernameToken>
			</wsp:Policy>
		</sp:SupportingTokens>
	</wsp:Policy>

	<wsp:Policy wsu:Id="ExamplePolicy2">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:TransportBinding>
					<wsp:Policy>
						<sp:TransportToken>
							<wsp:Policy>
								<sp:HttpsToken>
									<wsp:Policy />
								</sp:HttpsToken>
							</wsp:Policy>
						</sp:TransportToken>
						<sp:AlgorithmSuite>
							<wsp:Policy>
								<sp:Basic128 />
							</wsp:Policy>
						</sp:AlgorithmSuite>
					</wsp:Policy>
				</sp:TransportBinding>
				<sp:SupportingTokens>
					<wsp:Policy>
						<sp:UsernameToken
							sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
							<wsp:Policy>
								<sp:WssUsernameToken11 />
							</wsp:Policy>
						</sp:UsernameToken>
					</wsp:Policy>
				</sp:SupportingTokens>
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>

	<wsp:Policy wsu:Id="ExamplePolicy3">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:TransportBinding>
					<wsp:Policy>
						<sp:TransportToken>
							<wsp:Policy>
								<sp:HttpsToken>
									<wsp:Policy />
								</sp:HttpsToken>
							</wsp:Policy>
						</sp:TransportToken>
						<sp:AlgorithmSuite>
							<wsp:Policy>
								<sp:Basic128 />
							</wsp:Policy>
						</sp:AlgorithmSuite>
						<sp:IncludeTimestamp />
					</wsp:Policy>
				</sp:TransportBinding>
				<sp:SignedSupportingTokens>
					<wsp:Policy>
						<sp:SamlToken>
							<wsp:Policy>
								<sp:WssSamlV20Token11 />
							</wsp:Policy>
						</sp:SamlToken>
					</wsp:Policy>
				</sp:SignedSupportingTokens>
				<sp:Wss11>
					<wsp:Policy>
						<sp:MustSupportRefEmbeddedToken />
					</wsp:Policy>
				</sp:Wss11>
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>

	<wsp:Policy wsu:Id="ExamplePolicy4">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:TransportBinding>
					<wsp:Policy>
						<sp:TransportToken>
							<wsp:Policy>
								<sp:HttpsToken>
									<wsp:Policy />
								</sp:HttpsToken>
							</wsp:Policy>
						</sp:TransportToken>
						<sp:AlgorithmSuite>
							<wsp:Policy>
								<sp:Basic128 />
							</wsp:Policy>
						</sp:AlgorithmSuite>
						<sp:IncludeTimestamp />
					</wsp:Policy>
				</sp:TransportBinding>
				<sp:EndorsingSupportingTokens>
					<wsp:Policy>
						<sp:X509Token
							sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
							<wsp:Policy>
								<sp:WssX509V3Token10 />
							</wsp:Policy>
						</sp:X509Token>
						<sp:SignedParts>
							<sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
						</sp:SignedParts>
					</wsp:Policy>
				</sp:EndorsingSupportingTokens>
				<wsaw:UsingAddressing />
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>

	<wsp:Policy wsu:Id="ExamplePolicy5">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:TransportBinding>
					<wsp:Policy>
						<sp:TransportToken>
							<wsp:Policy>
								<sp:HttpsToken>
									<wsp:Policy />
								</sp:HttpsToken>
							</wsp:Policy>
						</sp:TransportToken>
						<sp:AlgorithmSuite>
							<wsp:Policy>
								<sp:Basic128 />
							</wsp:Policy>
						</sp:AlgorithmSuite>
						<sp:IncludeTimestamp />
					</wsp:Policy>
				</sp:TransportBinding>
				<sp:SignedSupportingTokens>
					<wsp:Policy>
						<sp:IssuedToken
							sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
							<sp:RequestSecurityTokenTemplate>
								<wst:TokenType>http://docs.oasis-open.org/wss/oasis-wss-saml-token-profile-1.1#SAMLV2.0
								</wst:TokenType>
								<wst:KeyType>http://docs.oasis-open.org/ws-sx/ws-trust/200512/Bearer
								</wst:KeyType>
							</sp:RequestSecurityTokenTemplate>
							<wsp:Policy>
								<sp:RequireInternalReference />
							</wsp:Policy>
							<sp:Issuer>
								<wsaw:Address>http://www.w3.org/2005/08/addressing/anonymous</wsaw:Address>
							</sp:Issuer>
						</sp:IssuedToken>
					</wsp:Policy>
				</sp:SignedSupportingTokens>
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>

	<wsp:Policy wsu:Id="ExamplePolicy6">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:TransportBinding>
					<wsp:Policy>
						<sp:TransportToken>
							<wsp:Policy>
								<sp:HttpsToken>
									<wsp:Policy />
								</sp:HttpsToken>
							</wsp:Policy>
						</sp:TransportToken>
						<sp:AlgorithmSuite>
							<wsp:Policy>
								<sp:Basic128 />
							</wsp:Policy>
						</sp:AlgorithmSuite>
						<sp:Layout>
							<wsp:Policy>
								<sp:Lax />
							</wsp:Policy>
						</sp:Layout>
						<sp:IncludeTimestamp />
					</wsp:Policy>
				</sp:TransportBinding>
				<sp:EndorsingSupportingTokens
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:SecureConversationToken
							sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/AlwaysToRecipient">
							<wsp:Policy>
								<sp:BootstrapPolicy>
									<wsp:Policy>
										<sp:SignedParts>
											<sp:Body />
											<sp:Header Name="To"
												Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
											<sp:Header Name="From"
												Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
											<sp:Header Name="FaultTo"
												Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
											<sp:Header Name="ReplyTo"
												Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
											<sp:Header Name="MessageID"
												Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
											<sp:Header Name="RelatesTo"
												Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
											<sp:Header Name="Action"
												Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
										</sp:SignedParts>
										<sp:EncryptedParts>
											<sp:Body />
										</sp:EncryptedParts>
										<sp:TransportBinding>
											<wsp:Policy>
												<sp:TransportToken>
													<wsp:Policy>
														<sp:HttpsToken />
													</wsp:Policy>
												</sp:TransportToken>
												<sp:AlgorithmSuite>
													<wsp:Policy>
														<sp:Basic128 />
													</wsp:Policy>
												</sp:AlgorithmSuite>
												<sp:Layout>
													<wsp:Policy>
														<sp:Strict />
													</wsp:Policy>
												</sp:Layout>
												<sp:IncludeTimestamp />
											</wsp:Policy>
										</sp:TransportBinding>
										<sp:SignedSupportingTokens>
											<wsp:Policy>
												<sp:UsernameToken
													sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/AlwaysToRecipient">
													<wsp:Policy>
														<sp:WssUsernameToken10 />
													</wsp:Policy>
												</sp:UsernameToken>
											</wsp:Policy>
										</sp:SignedSupportingTokens>
										<sp:Wss11>
											<wsp:Policy>
												<sp:MustSupportRefKeyIdentifier />
												<sp:MustSupportRefIssuerSerial />
												<sp:MustSupportRefThumbprint />
												<sp:MustSupportRefEncryptedKey />
											</wsp:Policy>
										</sp:Wss11>
										<sp:Trust10>
											<wsp:Policy>
												<sp:MustSupportIssuedTokens />
												<sp:RequireClientEntropy />
												<sp:RequireServerEntropy />
											</wsp:Policy>
										</sp:Trust10>
									</wsp:Policy>
								</sp:BootstrapPolicy>
							</wsp:Policy>
						</sp:SecureConversationToken>
						<sp:SignedParts>
							<sp:Header Name="To"
								Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
						</sp:SignedParts>
					</wsp:Policy>
				</sp:EndorsingSupportingTokens>
				<sp:Wss11>
					<wsp:Policy>
						<sp:MustSupportRefKeyIdentifier />
						<sp:MustSupportRefIssuerSerial />
						<sp:MustSupportRefThumbprint />
						<sp:MustSupportRefEncryptedKey />
					</wsp:Policy>
				</sp:Wss11>
				<sp:Trust10 xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:MustSupportIssuedTokens />
						<sp:RequireClientEntropy />
						<sp:RequireServerEntropy />
					</wsp:Policy>
				</sp:Trust10>
				<wsaw:UsingAddressing />
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>

	<wsp:Policy wsu:Id="ExamplePolicy7">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:TransportBinding>
					<wsp:Policy>
						<sp:TransportToken>
							<wsp:Policy>
								<sp:HttpsToken>
									<wsp:Policy />
								</sp:HttpsToken>
							</wsp:Policy>
						</sp:TransportToken>
						<sp:AlgorithmSuite>
							<wsp:Policy>
								<sp:Basic128 />
							</wsp:Policy>
						</sp:AlgorithmSuite>
						<sp:IncludeTimestamp />
					</wsp:Policy>
				</sp:TransportBinding>
				<sp:SignedSupportingTokens>
					<wsp:Policy>
						<sp:IssuedToken
							sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
							<sp:RequestSecurityTokenTemplate>
								<wst:TokenType>http://docs.oasis-open.org/wss/oasis-wss-saml-token-profile-1.1#SAMLV2.0
								</wst:TokenType>
								<wst:KeyType>http://docs.oasis-open.org/ws-sx/ws-trust/200512/Bearer
								</wst:KeyType>
							</sp:RequestSecurityTokenTemplate>
							<wsp:Policy>
								<sp:RequireInternalReference />
							</wsp:Policy>
							<sp:Issuer>
								<wsa:Address>http://www.w3.org/2005/08/addressing/anonymous</wsa:Address>
								<wsa:Metadata>
									<wsx:Metadata>
										<wsx:MetadataSection>
											<wsx:MetadataReference>
												<wsa:Address>https://localhost:8443/example/sts2/mex</wsa:Address>
											</wsx:MetadataReference>
										</wsx:MetadataSection>
									</wsx:Metadata>
								</wsa:Metadata>
							</sp:Issuer>
						</sp:IssuedToken>
					</wsp:Policy>
				</sp:SignedSupportingTokens>
				<wsam:Addressing wsp:Optional="false">
					<wsp:Policy />
				</wsam:Addressing>
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>

</definitions>