<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/"
	targetNamespace="urn:be:e-contract:sts:example" xmlns:tns="urn:be:e-contract:sts:example"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsoap12="http://schemas.xmlsoap.org/wsdl/soap12/"
	xmlns:wsp="http://www.w3.org/ns/ws-policy"
	xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
	xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702"
	xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:wst="http://docs.oasis-open.org/ws-sx/ws-trust/200512"
	xmlns:wsa="http://www.w3.org/2005/08/addressing" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata"
	xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex">

	<import location="example-base.wsdl" namespace="urn:be:e-contract:sts:example" />

	<binding name="ExampleServiceBinding" type="tns:ExampleServicePortType">
		<wsoap12:binding transport="http://schemas.xmlsoap.org/soap/http"
			style="document" />
		<operation name="echo">
			<wsp:PolicyReference URI="#ExamplePolicy" />
			<wsoap12:operation soapAction="echo" />
			<input>
				<wsoap12:body use="literal" />
			</input>
			<output>
				<wsoap12:body use="literal" />
			</output>
		</operation>
		<operation name="echoWithClaims">
			<wsp:PolicyReference URI="#ExamplePolicyWithClaims" />
			<wsoap12:operation soapAction="echoWithClaims" />
			<input>
				<wsoap12:body use="literal" />
			</input>
			<output>
				<wsoap12:body use="literal" />
			</output>
		</operation>
		<operation name="echoWithIdentityClaims">
			<wsp:PolicyReference URI="#ExamplePolicyWithIdentityClaims" />
			<wsoap12:operation soapAction="echoWithIdentityClaims" />
			<input>
				<wsoap12:body use="literal" />
			</input>
			<output>
				<wsoap12:body use="literal" />
			</output>
		</operation>
	</binding>

	<service name="ExampleService">
		<port name="ExampleServicePort" binding="tns:ExampleServiceBinding">
			<wsoap12:address location="https://www.e-contract.be/iam/example" />
		</port>
	</service>

	<wsp:Policy wsu:Id="ExamplePolicy">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:TransportBinding>
					<wsp:Policy>
						<sp:TransportToken>
							<wsp:Policy>
								<sp:HttpsToken>
									<wsp:Policy />
								</sp:HttpsToken>
							</wsp:Policy>
						</sp:TransportToken>
						<sp:AlgorithmSuite>
							<wsp:Policy>
								<sp:Basic128 />
							</wsp:Policy>
						</sp:AlgorithmSuite>
						<sp:IncludeTimestamp />
					</wsp:Policy>
				</sp:TransportBinding>
				<sp:SignedSupportingTokens>
					<wsp:Policy>
						<sp:IssuedToken
							sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
							<sp:RequestSecurityTokenTemplate>
								<wst:TokenType>http://docs.oasis-open.org/wss/oasis-wss-saml-token-profile-1.1#SAMLV2.0
								</wst:TokenType>
								<wst:KeyType>http://docs.oasis-open.org/ws-sx/ws-trust/200512/Bearer
								</wst:KeyType>
							</sp:RequestSecurityTokenTemplate>
							<wsp:Policy>
								<sp:RequireInternalReference />
							</wsp:Policy>
							<sp:Issuer>
								<wsa:Address>http://www.w3.org/2005/08/addressing/anonymous</wsa:Address>
								<wsa:Metadata>
									<wsx:Metadata>
										<wsx:MetadataSection>
											<wsx:MetadataReference>
												<wsa:Address>https://localhost/iam/sts/mex</wsa:Address>
											</wsx:MetadataReference>
										</wsx:MetadataSection>
									</wsx:Metadata>
								</wsa:Metadata>
							</sp:Issuer>
						</sp:IssuedToken>
					</wsp:Policy>
				</sp:SignedSupportingTokens>
				<wsam:Addressing wsp:Optional="false">
					<wsp:Policy />
				</wsam:Addressing>
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>

	<wsp:Policy wsu:Id="ExamplePolicyWithClaims">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:TransportBinding>
					<wsp:Policy>
						<sp:TransportToken>
							<wsp:Policy>
								<sp:HttpsToken>
									<wsp:Policy />
								</sp:HttpsToken>
							</wsp:Policy>
						</sp:TransportToken>
						<sp:AlgorithmSuite>
							<wsp:Policy>
								<sp:Basic128 />
							</wsp:Policy>
						</sp:AlgorithmSuite>
						<sp:IncludeTimestamp />
					</wsp:Policy>
				</sp:TransportBinding>
				<sp:SignedSupportingTokens>
					<wsp:Policy>
						<sp:IssuedToken
							sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
							<sp:RequestSecurityTokenTemplate>
								<wst:TokenType>http://docs.oasis-open.org/wss/oasis-wss-saml-token-profile-1.1#SAMLV2.0
								</wst:TokenType>
								<wst:KeyType>http://docs.oasis-open.org/ws-sx/ws-trust/200512/Bearer
								</wst:KeyType>
								<wst:Claims Dialect="http://schemas.xmlsoap.org/ws/2005/05/identity">
									<wsid:ClaimType
										xmlns:wsid="http://schemas.xmlsoap.org/ws/2005/05/identity"
										Uri="urn:be:e-contract:iam:claims:self-claimed:office-key" />
									<wsid:ClaimType
										xmlns:wsid="http://schemas.xmlsoap.org/ws/2005/05/identity"
										Uri="urn:be:e-contract:iam:claims:self-claimed:software-key" />
								</wst:Claims>
							</sp:RequestSecurityTokenTemplate>
							<wsp:Policy>
								<sp:RequireInternalReference />
							</wsp:Policy>
							<sp:Issuer>
								<wsa:Address>http://www.w3.org/2005/08/addressing/anonymous</wsa:Address>
								<wsa:Metadata>
									<wsx:Metadata>
										<wsx:MetadataSection>
											<wsx:MetadataReference>
												<wsa:Address>https://localhost/iam/sts/mex</wsa:Address>
											</wsx:MetadataReference>
										</wsx:MetadataSection>
									</wsx:Metadata>
								</wsa:Metadata>
							</sp:Issuer>
						</sp:IssuedToken>
					</wsp:Policy>
				</sp:SignedSupportingTokens>
				<wsam:Addressing wsp:Optional="false">
					<wsp:Policy />
				</wsam:Addressing>
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>
	
	<wsp:Policy wsu:Id="ExamplePolicyWithIdentityClaims">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:TransportBinding>
					<wsp:Policy>
						<sp:TransportToken>
							<wsp:Policy>
								<sp:HttpsToken>
									<wsp:Policy />
								</sp:HttpsToken>
							</wsp:Policy>
						</sp:TransportToken>
						<sp:AlgorithmSuite>
							<wsp:Policy>
								<sp:Basic128 />
							</wsp:Policy>
						</sp:AlgorithmSuite>
						<sp:IncludeTimestamp />
					</wsp:Policy>
				</sp:TransportBinding>
				<sp:SignedSupportingTokens>
					<wsp:Policy>
						<sp:IssuedToken
							sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
							<sp:RequestSecurityTokenTemplate>
								<wst:TokenType>http://docs.oasis-open.org/wss/oasis-wss-saml-token-profile-1.1#SAMLV2.0
								</wst:TokenType>
								<wst:KeyType>http://docs.oasis-open.org/ws-sx/ws-trust/200512/Bearer
								</wst:KeyType>
								<wst:Claims Dialect="http://schemas.xmlsoap.org/ws/2005/05/identity">
									<wsid:ClaimType
										xmlns:wsid="http://schemas.xmlsoap.org/ws/2005/05/identity"
										Uri="urn:be:e-contract:iam:claims:self-claimed:office-key" />
									<wsid:ClaimType
										xmlns:wsid="http://schemas.xmlsoap.org/ws/2005/05/identity"
										Uri="urn:be:e-contract:iam:claims:self-claimed:software-key" />
									<wsid:ClaimType
										xmlns:wsid="http://schemas.xmlsoap.org/ws/2005/05/identity"
										Uri="http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname" />
								</wst:Claims>
							</sp:RequestSecurityTokenTemplate>
							<wsp:Policy>
								<sp:RequireInternalReference />
							</wsp:Policy>
							<sp:Issuer>
								<wsa:Address>http://www.w3.org/2005/08/addressing/anonymous</wsa:Address>
								<wsa:Metadata>
									<wsx:Metadata>
										<wsx:MetadataSection>
											<wsx:MetadataReference>
												<wsa:Address>https://localhost/iam/sts/mex
												</wsa:Address>
											</wsx:MetadataReference>
										</wsx:MetadataSection>
									</wsx:Metadata>
								</wsa:Metadata>
							</sp:Issuer>
						</sp:IssuedToken>
					</wsp:Policy>
				</sp:SignedSupportingTokens>
				<wsam:Addressing wsp:Optional="false">
					<wsp:Policy />
				</wsam:Addressing>
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>

</definitions>